title: Open School Brasil
description: Uma escola aberta, da comunidade, para a comunidade!
email: openschoolbr@gmail.com
user: openschoolbr
baseurl: ""

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock